config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'
  get '/search', to: 'listings#search', as: 'search'
  get 'welcome/index'
  resources :listings do
    resources :bookings, only: [:create]
  end
  post 'braintree/checkout'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "users"
  resources :bookings, only: [:create, :destroy]
  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  resources :bookings, only: [:destroy] do
      resources :braintree, only: [:new, :create]
    end
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :photos, :dependent => :destroy
  has_many :bookings, :dependent => :destroy
  searchkick match: :word_start, searchable: [:price]
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]


  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.paginate(:page => params[:page]).per_page(5)
  end

  def search
      @listings = Listing.search(params[:term], fields: [price: :exact])
      if @listings.blank?
        redirect_to listings_path, flash:{danger: "no successful search result"}
      else
        render :index
      end
end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @booking = @listing.bookings.new
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.new(listing_params)
    respond_to do |format|
      if @listing.save
        store_photos

        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def store_photos
    photos = params[:listing][:photos]
    photos.each{|photo| @listing.photos.create(image: photo)} if photos
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:description, :address, :number_of_rooms, :photos, :max_guest, :price)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(listing) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :number_of_rooms %>
    <%= f.number_field :number_of_rooms %>
  </div>

  <div class="field">
    <%= f.label :max_guest %>
    <%= f.number_field :max_guest %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :photos %>
    <%= f.file_field :photos, multiple: true%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>
<!-- beginning of search form -->
<div class="search">
  <%= form_tag search_path, method: "get", class: "navbar-form navbar-left" do |f| %>
    <%= text_field_tag :term, params[:term],placeholder:"price" %>
    <%= submit_tag 'search', class: 'btn btn-primary' %>
    <!-- end of search form -->
  <% end %>
  <!-- end of search div -->
</div>
<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Description</th>
      <th>Address</th>
      <th>Number of rooms</th>
      <th>Max Guest</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.user.name %></td>
        <td><%= listing.description %></td>
        <td><%= listing.address %></td>
        <td><%= listing.number_of_rooms %></td>
        <td><%= listing.max_guest %></td>
        <td><%= listing.price %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

<%= will_paginate @listing %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @listing.user.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>Number of rooms:</strong>
  <%= @listing.number_of_rooms %>
</p>

<p>
  <strong>Picture</strong>
  <% @listing.photos.each do |photo| %>
    <%= image_tag photo.image.thumb.url %>
  <% end %>
  <%# @listing.photos.each do |photo| %>
      <%# cl_image_tag(photo.url) %>
  <%# end %>
</p>


<%= render "bookings/form" %>
<%= link_to 'Edit', edit_listing_path(@listing) %>
<%= link_to 'Back', listings_path %>