config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'
  get '/search', to: 'listings#search', as: 'search'
  get 'welcome/index'
  resources :listings do
    resources :bookings, only: [:create]
  end
  post 'braintree/checkout'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "users"
  resources :bookings, only: [:create, :destroy]
  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  resources :bookings, only: [:destroy] do
      resources :braintree, only: [:new, :create]
    end
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :authentications, :dependent => :destroy
  has_many :listings, :dependent => :destroy
  has_many :bookings, :dependent => :destroy
  enum access_level: [:customer => 0, :moderator =>1, :super_admin =>2]
  mount_uploaders :photo, PhotoUploader

  def self.create_with_auth_and_hash(authentication, auth_hash)
      user = User.create!(name: auth_hash["extra"]["raw_info"]["name"], email: auth_hash["extra"]["raw_info"]["email"], age: auth_hash["extra"]["raw_info"]["age_range"].min[1], birthday: auth_hash["extra"]["raw_info"]["birthday"], gender:  auth_hash["extra"]["raw_info"]["gender"])
      user.authentications << (authentication)
      return user
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def new
    @user = User.new()
    render template: "users/new"
  end

  def show
    @user = User.find(params[:id])
    @bookings = @user.bookings
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      redirect_back_or url_after_create

    else
      # render template: "users/new"
      respond_to do |format|
        format.html { render template: "users/new" }
        format.js
      end
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  # def user_from_params
  #   email = user_params.delete(:email)
  #   password = user_params.delete(:password)

  #   Clearance.configuration.user_model.new(user_params).tap do |user|
  #     user.email = email
  #     user.password = password
  #   end
  # end

  def user_params
  	params.require(:user).permit(:name, :age, :email, :password, :gender, :photo)
  end
  # def user_params
  #   params[Clearance.configuration.user_parameter] || Hash.new
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div class="text-field">
  <%= form.label :gender %>
  <%= form.text_field :gender %>
</div>


<div class="text-field">
  <%= form.label :age %>
  <%= form.text_field :age %>
</div>

<div class="text-field">
  <%= form.label :birthday %>
  <%= form.text_field :birthday %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="file_field">
  <%= form.label :photo %>
  <%= form.file_field :photo %>
</div>

app/views/users/create.js.erb
$('$.container').html(<%= @user.errors.full_messages %>)
    

app/views/users/index.html.erb
<% @users.each do |x| %>
<%= x.email %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>My listings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Description</th>
      <th>Address</th>
      <th>Number of rooms</th>
      <th>Max Guests</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.listings.each do |x| %>
      <tr>
        <td><%= x.user.name %></td>
        <td><%= x.description %></td>
        <td><%= x.address %></td>
        <td><%= x.number_of_rooms %></td>
        <td><%= x.max_guest %></td>
        <td><%= x.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h1>My booking</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Number of guests</th>
      <th>Total Price</th>
      <th>Action</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @bookings.each do |booking| %>
    <tr>
    <td><%= link_to booking.listing.description, booking.listing %></td>
    <td><%= booking.start_date.strftime('%d %B %Y') %></td>
    <td><%= booking.end_date.strftime('%d %B %Y') %></td>
    <td><%= booking.num_of_guests %></td>
    <td><%= booking.total_price %></td>
    <td><%= link_to "Cancel Booking", booking, method: :delete %></td>
    <td><%= link_to "Make Payment", new_booking_braintree_path(booking) %></td>
    </tr>
    <% end %>
</table>
<%= link_to 'Back to listings', listings_path %>